### ISSUE TITLE
TYPO3 7.x | Invalid argument supplied for foreach() in module index

### ISSUE THREAD

**Issue by inrivagmbh** [Bunnyfield/l10nmgr#1]
Just started testing the current state in 7.x, first error appears after starting the module index:
Core: Error handler (BE): PHP Warning: Invalid argument supplied for foreach() in /typo3conf/ext/l10nmgr/Classes/Modules/Module1/index.php line 30

**Comment by Bunnyfield** [comment]
Will be taken care of, when we officially start to support CMS 7 on master and branched 6.2 support into 5-0
