### ISSUE TITLE
Nested "empty" Fluid Container

### ISSUE THREAD

**Issue by onigunn** [Bunnyfield/l10nmgr#4]
Since the last commit l10nmgr is now aware of "empty" fluid content elements which host different child elements - this behaviour seems to be not recursively. If I place my first empty element into a second one then only the first parent of my text elements will be translated. E.g.

```
content-wrapper
* content-grid
** text left
** text right
```

Resulting XML export will only hold `content-grid` and his childs which leads to a completed import but elements will not appear because `content-wrapper`. 

This seems to be caused by `\Localizationteam\L10nmgr\View\CatXmlView` ignoring items which don't hold `fields`. Simple adding them doesn't solve the problem because on import we'll get following error:

`These fields were ignored since they were not in the configuration:`

Probably we could work on this together, maybe you already aware of it too and I would like to contribute some help if possible.

**Comment by Bunnyfield** [comment]
Please check out latest master and give some feedback when it works for you.

**Comment by onigunn** [comment]
My starting point of just exporting everything was based of incomplete information how the export/import works in detail. Thanks for the fast response, I'll give it a try tomorrow.

**Comment by onigunn** [comment]
I've got sometime to test your latest changes: Sadly, it doesn't work. Beside of that you got a bug in your latest commit. `$this->TCA` is empty so you will raise an exception on `recursivelyCheckForRelationParents` - If you like a could open a pull-request for that.

**Comment by Bunnyfield** [comment]
Will revert the latest change for convenience reasons now and come up with a fix - sorry - was too quick and dirty yesterday

**Comment by Bunnyfield** [comment]
$TCA must stay global instead of moving it to $this

**Comment by Bunnyfield** [comment]
Done - please check again :-)

**Comment by onigunn** [comment]
Awesome. My first tests are working. Thanks for your fast response here!
