### ISSUE TITLE
Excel/XML Export no Content in it. XML not consistent

### ISSUE THREAD

**Issue by DirkPersky** [Bunnyfield/l10nmgr#8]
Hello,

i love to use your Extension but you have 2 errors found in it.

**My System:**
TYPO3: 7LTS (latest)
PHP: 5.6
l10nmg: **v5** and latest **v7 git**

**First: (cat)XML not consistent:**
You dont wrap all Translation in: `<![CDATA[ ..... ]]` which course an error at the import to Excel. As you can see in the attachted files i only get 1 CDATA but i need it many times more. So here is something not working Correctly.

Also there is an `<!DOCTYPE TYPO3L10N [ <!ENTITY nbsp " "> ]>` which course an Error to in MS-Excel.

**Excel/XML Export no Content**
As you can see in the attached file i always get an **Empty element!** for each text.
The _Online Translation_ or _XML export like above_ works, but the Excel/XML dont.

I Hope you will fix that issue as sone as possible.
[export.zip](https://github.com/Bunnyfield/l10nmgr/files/254654/export.zip)

**Comment by Bunnyfield** [comment]
Please report issues on https://forge.typo3.org/projects/extension-l10nmgr/issues now - this repo will be closed down soon.
